### PR TITLE
docs: write about the deep selector on README

### PR DESCRIPTION
**Pull request by Avantgarde95**
* About `/deep/`
* About the alternative method

### CODE REVIEW

**Review by NikosDev — APPROVED** [review]

**Comment by Heliodromel** [comment]
Hi,
I have a question about the alternative method : it seems to be an alternative only when using Vue. Are you aware of something similar when using this project with reactjs ?

Thanks,

**Comment by Avantgarde95** [comment]
> Hi, I have a question about the alternative method : it seems to be an alternative only when using Vue. Are you aware of something similar when using this project with reactjs ?
> 
> Thanks,

It might work with React, too. I used that method in the React-based project. (I think that `@vue/component-compiler-utils` is used internally and it doesn't make any problems with React.)

**Comment by Heliodromel** [comment]
Oh ok, i see and do you have any clue how to load @vue/component-compiler-utils in a react project. Does it mean i should add "vue-loader" to my webpack config ?

**Comment by Heliodromel** [comment]
Actually, looking at the code (packages/scoped-css-loader/index.js) i can see that @vue/component-compiler-utils is already used by this plugin to deal with the scoped style so i guess the ::v-deep directive should work out of the box, even in my react project.

However, the sass-loader runs first when dealing with my *.scoped.scss files and sass is telling that it does not recognize ::v-deep pseudo element.

How does it work for you in Vue project ? Do you have another loader which runs before sass-loader which rewrites/replace somehow ::v-deep pseudo element with something else ?

**Pull request merged**
