### PR TITLE
allow .sass files

### PR DESCRIPTION
**Pull request by Ni55aN**

### CODE REVIEW

**Comment by gaoxiaoliangz** [comment]
You can do that by adding options in babel config like this

```
"plugins": [["babel-plugin-react-scoped-css", {
  "include": "\.scoped\.(sa|sc|c)ss$"
}]]
```

**Comment by Ni55aN** [comment]
Thanks, I'll try

**Comment by Ni55aN** [comment]
In another case, the support of all three extensions by default does not hurt. After all `.scss` supported

**Comment by gaoxiaoliangz** [comment]
Yes, I think you made a point. This should be supported out of the box.

**Pull request merged**
